### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by hawkoon** [hrik2001/RikChan#3]
What happened to https://rikchan.pythonanywhere.com/ ?

**Comment by hrik2001** [comment]
I have no idea, it keeps getting down and apparently its a problem with https://pythonaywhere.com

**Comment by hrik2001** [comment]
So I talked to the people there and turns out I hadnt logged back into my account for 3 months, which is why they downed the website assuming it was inactive

**Comment by hawkoon** [comment]
> I hadnt logged back into my account for 3 months

Lol. You should do more programming and fix or add features so you are forced to login and update stuff. Anyway glad it's back online.
