### ISSUE TITLE
How am I supposed to login as an admin?

### ISSUE THREAD

**Issue by Mr-Steal-Your-Script** [hrik2001/RikChan#4]
going to ```/_ct_``` just tells me:

>lol go away

lmao

**Comment by hrik2001** [comment]
1) Make sure you are logged in lol.
2) Use
`python account.py <username> <password> <rank number>` to generate an account (rank number 2 for admin)

**Comment by Mr-Steal-Your-Script** [comment]
But where do I login at?

**Comment by hrik2001** [comment]
`/login`

**Comment by Mr-Steal-Your-Script** [comment]
Thanks!
